---
- name: Voeg een OAuth-client toe aan IBM ISAM
  hosts: isam
  gather_facts: no

  tasks:
    - name: "add 0authclient"
      ansible.builtin.include_role:
        name: ibm.isam.add_oauth_client
      vars:
        # Dynamisch de variabelen instellen alleen als ze gedefinieerd zijn
        set_oauth_client_clientId: "{{ clientId | default(omit) }}"
        set_oauth_client_clientSecret: "{{ clientSecret | default(omit) }}"
        set_oauth_client_companyName: "{{ companyName | default(add_oauth_client_companyName) }}"
        set_oauth_client_definitionName: "{{ definitionName | default(omit) }}"
        set_oauth_client_name: "{{ client_name | default(omit) }}"
        set_oauth_client_redirectUri: "{{ redirectUri | default(omit) }}"
        set_oauth_client_requirePkce: "{{ requirePkce | default(omit) }}"
        set_oauth_client_companyUrl: "{{ companyUrl | default(omit) }}"
        set_oauth_client_contactPerson: "{{ contactPerson | default(omit) }}"
        set_oauth_client_contactType: "{{ contactType | default(omit) }}"
        set_oauth_client_email: "{{ email | default(omit) }}"
        set_oauth_client_phone: "{{ phone | default(omit) }}"
        set_oauth_client_otherInfo: "{{ otherInfo | default(omit) }}"
        set_oauth_client_encryptionDb: "{{ encryptionDb | default(omit) }}"
        set_oauth_client_encryptionCert: "{{ encryptionCert | default(omit) }}"
        set_oauth_client_jwksUri: "{{ jwksUri | default(omit) }}"
        set_oauth_client_extProperties: "{{ extProperties | default(omit) }}"
