- name: Maak directories aan
  hosts: all
  become: yes

  tasks:
    - name: Probeer een subdirectory aan te maken zonder parent
      recurse: no
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop: "{{ directories }}"
      register: result
      ignore_errors: no
