- name: Test gefaalde variabelen opvangen
  hosts: all
  become: yes

  vars:
    test_variabelen:
      - "correcte_waarde"
      - "fout_waarde"
      - "nog_een_correcte_waarde"
      - "nog_een_fout"

  tasks:
    - name: Simuleer een fout bij bepaalde variabelen
      command: "echo {{ item }}"
      loop: "{{ test_variabelen }}"
      register: resultaat
      failed_when: "'fout' in item" # Als de variabele "fout" bevat, laten we de taak falen

    - name: Verzamel mislukte variabelen
      set_fact:
        mislukte_variabelen: "{{ mislukte_variabelen | default([]) + [item.item] }}"
      loop: "{{ resultaat.results }}"
      when: item.failed | default(false)

    - name: Toon mislukte variabelen (voor debugging)
      debug:
        msg: "De volgende variabelen zijn mislukt: {{ mislukte_variabelen }}"
      when: mislukte_variabelen | default([]) | length > 0

    - name: Gebruik de mislukte variabelen in een andere taak
      debug:
        msg: "De mislukte variabelen kunnen hier gebruikt worden: {{ mislukte_variabelen }}"
      when: mislukte_variabelen | default([]) | length > 0
