- name: Maak directories aan
  hosts: all
  become: yes

  tasks:
    - name: Controleer of de parent directory bestaat
      ansible.builtin.stat:
        path: "{{ item | dirname }}"
      loop: "{{ directories }}"
      register: parent_dirs

    - name: Forceer een fout als de parent directory niet bestaat
      ansible.builtin.fail:
        msg: "Parent directory ontbreekt voor {{ item }}"
      loop: "{{ directories }}"
      when: not parent_dirs.results[loop.index0].stat.exists

    - name: Maak de directories aan (wordt alleen uitgevoerd als de parent bestaat)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop: "{{ directories }}"
