- name: Maak directories aan
  hosts: all
  become: yes

  tasks:
    - name: Creëer directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop: "{{ directories }}"
