---
- name: Playbook voor mislukte hosts verzamelen
  hosts: machines
  gather_facts: no
  tasks:
    - name: Test bereikbaarheid
      ping:
      register: ping_result
      ignore_unreachable: yes
      ignore_errors: yes

    - name: Toon mislukte hosts
      debug:
        msg: "Mislukte hosts: {{ ansible_play_hosts_all }}"
      run_once: yes
