---
- name: Playbook voor mislukte hosts verzamelen
  hosts: machines
  gather_facts: no
  tasks:
    - name: Test bereikbaarheid
      ping:
      register: ping_result
      ignore_unreachable: yes
      ignore_errors: yes

    - name: Voeg mislukte hosts toe aan variabele
      run_once: yes
      set_fact:
        failed_hosts: "{{ ansible_play_hosts | select('in', ansible_play_hosts_failed | default([])) | list }}"

    - name: Toon mislukte hosts
      debug:
        msg: "Mislukte hosts: {{ failed_hosts }}"
      run_once: yes
