- name: Verwerken van machines
  hosts: machines
  gather_facts: yes
  tasks:
    - name: Voeg tag toe aan succesvolle hosts
      set_fact:
        tagged_as_successful: true

    - name: Voeg gelukte hosts toe aan de groep 'gelukte_hosts'
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: gelukte_hosts
      loop: "{{ ansible_play_hosts }}"
      when: "'tagged_as_successful' in hostvars[item]"

    - name: Toon de verzamelde gelukte hosts
      run_once: true
      debug:
        msg: "{{ groups['gelukte_hosts'] }}"

    - name: voeg mislukte hosts aan variabelen
      run_once: true
      set_fact:
        mislukte_hosts: "{{ (ansible_play_hosts_all | difference(groups['gelukte_hosts'])) }}"

    - name: Toon gefaalde hosts
      run_once: true
      debug:
        msg: "{{ mislukte_hosts }}"

    - name: Verzend mislukte hosts naar custom inventory module
      inventory:
        mislukte_hosts: "{{ mislukte_hosts }}"
        playbook_name: "{{ playbook_name }}"
      when: mislukte_hosts | length > 0
      register: output
      run_once: yes
