---
- name: Playbook voor mislukte hosts verzamelen
  hosts: machines
  gather_facts: no
  tasks:
    - name: Initialiseerlijst voor mislukte hosts
      set_fact:
        failed_hosts: []
      run_once: yes
      delegate_to: localhost

    - name: Test bereikbaarheid
      ping:
      register: ping_result
      ignore_unreachable: yes
      ignore_errors: yes

    - name: Voeg mislukte hosts toe aan variabele via controller
      delegate_to: localhost
      run_once: yes
      set_fact:
        failed_hosts: "{{ failed_hosts + [item] }}"
      with_items: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"

    - name: Toon mislukte hosts
      debug:
        msg: "Mislukte hosts: {{ failed_hosts }}"
      run_once: yes
      delegate_to: localhost
