---
- name: Playbook voor mislukte hosts verzamelen
  hosts: machines
  gather_facts: no
  tasks:
    - name: Test bereikbaarheid
      ping:
      register: ping_result
      ignore_unreachable: yes
      ignore_errors: yes

    - name: Voeg mislukte hosts toe aan variabele
      delegate_to: localhost
      run_once: yes
      set_fact:
        failed_hosts: >-
          {{ ansible_run_hosts | difference(ansible_play_hosts) | list }}

    - name: Toon mislukte hosts
      debug:
        msg: "Mislukte hosts: {{ failed_hosts }}"
      run_once: yes
