- name: Playbook voor inventory's te maken
  hosts: machines
  gather_facts: yes
  tasks:
    - name: Voeg gelukte hosts toe aan variabele
      set_fact:
        gelukte_hosts: "{{ gelukte_hosts + [inventory_hostname] if gelukte_hosts is defined else [inventory_hostname] }}"

    - name: Toon gelukte hosts (debug)
      debug:
        msg: "{{ gelukte_hosts }}"
      when: inventory_hostname == gelukte_hosts[-1] # Check of dit de laatste succesvolle host is
      run_once: yes

    - name: Voeg mislukte hosts toe aan variabele (alleen op de laatste succesvolle host)
      set_fact:
        mislukte_hosts: "{{ (ansible_play_hosts_all | difference(gelukte_hosts)) }}"
      when: inventory_hostname == gelukte_hosts[-1] # Check of dit de laatste succesvolle host is
      run_once: yes

    - name: Verzend mislukte hosts naar custom inventory module
      inventory:
        mislukte_hosts: "{{ mislukte_hosts }}"
      when: mislukte_hosts | length > 0
      register: output
      run_once: yes

    - name: Toon hosts
      debug:
        msg:
          - "succesvolle hosts: {{ gelukte_hosts | default([]) }}"
          - "mislukte hosts: {{ mislukte_hosts | default([]) }}"
          - "alle hosts: {{ ansible_play_hosts_all }}"
      run_once: yes
