- name: Playbook voor inventory's te maken
  hosts: machines
  gather_facts: yes
  tasks:
    - name: Voeg gelukte hosts toe aan variabele
      set_fact:
        gelukte_hosts: "{{ (gelukte_hosts | default([])) + [inventory_hostname] }}"
      when: ansible_facts['network']['hostname'] != 'unreachable' # Alleen als de host bereikbaar is

    - name: Verzamel mislukte hosts op de laatste succesvolle host
      set_fact:
        mislukte_hosts: "{{ (ansible_play_hosts_all | difference(gelukte_hosts)) }}"
      when: inventory_hostname == ansible_play_hosts_all[-1] # Alleen op de laatste host
      run_once: yes

    - name: Verzend mislukte hosts naar custom inventory module
      inventory:
        mislukte_hosts: "{{ mislukte_hosts }}"
      when: mislukte_hosts | length > 0
      register: output
      run_once: yes

    - name: Toon hosts
      debug:
        msg:
          - "succesvolle hosts: {{ gelukte_hosts | default([]) }}"
          - "mislukte hosts: {{ mislukte_hosts | default([]) }}"
          - "alle hosts: {{ ansible_play_hosts_all }}"
      run_once: yes
