---
- name: Playbook voor inventory's te maken
  hosts: machines
  gather_facts: yes
  tasks:
    - name: Voeg mislukte hosts toe aan variabele
      set_fact:
        failed_hosts: "{{ failed_hosts | default([]) + [inventory_hostname] }}"

    - name: Toon mislukte hosts
      debug:
        msg:
          - "succesvolle hosts: {{ failed_hosts | default([]) }}"
          - "alle hosts: {{ ansible_play_hosts_all }}"
      run_once: yes
