---
- name: Playbook voor inventory's te maken
  hosts: machines
  gather_facts: no
  tasks:
    - name: Voeg mislukte hosts toe aan variabele
      set_fact:
        failed_hosts: "{{ failed_hosts | default([]) + [inventory_hostname] }}"

    - name: Toon mislukte hosts
      debug:
        msg: "Mislukte hosts: {{ failed_hosts | default([]) }}"
      run_once: yes
