- name: Playbook voor inventory's te maken
  hosts: machines
  gather_facts: yes
  tasks:
    - name: Voeg gelukte hosts toe aan variabele
      set_fact:
        gelukte_hosts: "{{ (gelukte_hosts | default([])) + [inventory_hostname] }}"

    - name: Toon hosts
      debug:
        msg:
          - "succesvolle hosts: {{ gelukte_hosts | default([]) }}"
          - "alle hosts: {{ ansible_play_hosts_all }}"
      run_once: yes
