---
- name: Playbook met foutafhandeling
  hosts: 192.168.242.157
  gather_facts: yes
  run_once: true
  vars_files:
    - vars.yml # Zorg dat deze file bestaat en correct wordt ingeladen

  tasks:
    - name: Simuleer een fout
      command: /bin/false
      ignore_errors: yes
      register: command_result

    - name: Verzamel alleen variabelen uit vars.yml
      set_fact:
        failed_hosts: "{{ ansible_play_hosts_all }}"
        custom_vars: "{{ vars | dict2items | selectattr('key', 'in', ['nieuwe_hostname', 'extra_test']) | items2dict }}"
      when: command_result.rc != 0

    - name: Toon opgeslagen informatie
      debug:
        msg:
          - "Mislukte hosts: {{ failed_hosts }}"
          - "Custom variabelen uit vars.yml: {{ custom_vars }}"
      when: command_result.rc != 0
