---
- name: Playbook met foutafhandeling
  hosts: machines
  gather_facts: yes
  vars_files:
    - vars.yml # Zorg dat de variabelenfile correct wordt ingeladen

  tasks:
    - name: Simuleer een fout
      command: /bin/false
      ignore_errors: yes
      register: command_result

    - name: Verzamel alleen de variabelen gedefinieerd in vars.yml
      run_once: true
      set_fact:
        failed_hosts: "{{ ansible_play_hosts_all }}"
        custom_vars: "{{ hostvars[inventory_hostname] | dict2items | selectattr('key', 'search', '^.*$') | selectattr('key', 'match', '^([^ansible_].*)$') | items2dict }}"
      when: command_result.rc != 0

    - name: Toon opgeslagen informatie
      run_once: true
      debug:
        msg:
          - "Mislukte hosts: {{ failed_hosts }}"
          - "Custom variabelen uit vars.yml: {{ custom_vars }}"
      when: command_result.rc != 0
