---
- name: Playbook om alleen de variabelen uit vars.yml te tonen
  hosts: machines
  gather_facts: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Toon alleen de variabelen die in vars.yml zijn gedefinieerd
      debug:
        msg: |
          {% set excluded_keys = [
            'ansible_facts', 
            'ansible_verbosity', 
            'ansible_check_mode', 
            'ansible_diff_mode', 
            'ansible_inventory_sources', 
            'ansible_playbook_python', 
            'ansible_run_tags', 
            'ansible_skip_tags', 
            'ansible_version', 
            'command_result', 
            'groups', 
            'inventory_file', 
            'inventory_dir', 
            'inventory_hostname', 
            'inventory_hostname_short', 
            'playbook_dir', 
            'semaphore_vars', 
            'omit'
          ] %}

          {% set custom_vars = hostvars[inventory_hostname] | dictsort %}
          {% set filtered_vars = custom_vars | selectattr(0, 'not in', excluded_keys) | list %}
          {{ filtered_vars | to_nice_json }}
