---
- name: Playbook met foutafhandeling
  hosts: machines
  gather_facts: no
  vars_files:
    - vars.yml # Zorg dat de variabelenfile correct wordt ingeladen

  tasks:
    - name: Simuleer een fout
      command: /bin/false
      ignore_errors: yes
      register: command_result

    - name: Verzamel alle variabelen uit hostvars
      run_once: true
      set_fact:
        failed_hosts: "{{ ansible_play_hosts_all }}"
        _special_vars:
          - ansible_dependent_role_names
          - ansible_play_batch
          - ansible_play_hosts
          - ansible_play_hosts_all
          - ansible_play_name
          - ansible_play_role_names
          - ansible_role_names
          - environment
          - hostvars
          - play_hosts
          - role_names
        _hostvars: "{{ hostvars[inventory_hostname] | dict2items | map(attribute='key') | list }}"
        _my_vars: "{{ vars.keys() |
          difference(_hostvars) |
          difference(_special_vars) |
          reject('match', '^_.*$') |
          list |
          sort }}"
        custom_vars: "{{ dict(_my_vars | zip(lookup('vars', _my_vars))) | to_nice_json }}"
      when: command_result.rc != 0

    - name: Toon opgeslagen informatie
      run_once: true
      debug:
        msg:
          - "Mislukte hosts: {{ failed_hosts }}"
          - "Custom variabelen uit vars.yml: {{ custom_vars }}"
      when: command_result.rc != 0
