---
- name: Playbook met foutafhandeling
  hosts: machines
  gather_facts: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Simuleer een fout
      command: /bin/false
      ignore_errors: yes
      register: command_result

    - name: Verzamel variabelen tussen group_names en command_result
      run_once: true
      set_fact:
        failed_hosts: "{{ ansible_play_hosts_all }}"
        custom_vars: >-
          {{
            hostvars[inventory_hostname] |
            dict2items |
            selectattr('key', 'search', '^.*$') |
            selectattr('key', 'search', '^(?!command_result$).*') |
            selectattr('key', 'search', '^(?!semaphore_vars$).*') |
            selectattr('key', 'search', '^(?!playbook_dir$).*') |
            selectattr('key', 'search', '^(?!groups$).*') |
            items2dict
          }}
      when: command_result.rc != 0

    - name: Toon opgeslagen informatie
      run_once: true
      debug:
        msg:
          - "Mislukte hosts: {{ failed_hosts }}"
          - "Custom variabelen uit vars.yml: {{ custom_vars }}"
      when: command_result.rc != 0
