- name: Beheer Semaphore configuratie
  hosts: machines
  gather_facts: no
  tasks:
    - name: Start het blok van taken en simuleer een fout
      block:
        - name: Voer een ongeldige opdracht uit (dit zal falen)
          ansible.builtin.command:
            cmd: nonexistent_command
          ignore_errors: no
      rescue:
        - name: hosts kopieren
          ansible.builtin.copy:
            src: inventori/hosts
            dest: .
        - name: variablen kopieren
          ansible.builtin.copy:
            src: inventori/host_vars/192.168.242.157/vars.yml
            dest: .
        - name: Voer de Semaphore manager uit
          semaphore_manager:
          register: semaphore_output

        - name: Toon de output van Semaphore
          debug:
            msg: "De Semaphore Manager is uitgevoerd. Resultaat: {{ semaphore_output }}"
        - name: Verwijder het hosts bestand van de doelserver
          ansible.builtin.file:
            path: hosts
            state: absent
        - name: Verwijder het variabelen bestand van de doelserver
          ansible.builtin.file:
            path: vars.yml
            state: absent
