- name: Test custom Python module
  hosts: machines
  gather_facts: no
  tasks:
    - name: Run mijn custom module
      module:
      register: output

    - name: Toon output
      debug:
        msg: "{{ output }}"
