---
- name: Read variables from GitHub repo
  hosts: localhost

  tasks:
    - name: Read variables from vars.yml
      include_vars:
        file: client-configurations/DEV/testClient.yml

    - name: Display variables
      debug:
        msg:
          - "Client Name: {{ client_name }}"
          - "Definition Name: {{ definition_name }}"
          - "Company Name: {{ company_name }}"
          - "Redirect URIs: {{ redirect_uri }}"
          - "Client ID: {{ client_id }}"
          - "Client Secret: {{ client_secret }}"
          - "Require PKCE: {{ require_pkce }}"
          - "Ext Properties: {{ extProperties }}"
