---
- name: Clone or pull GitHub repo and read variables
  hosts: localhost
  vars_files:
    - vars.yml

  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present

    - name: Check if the repository exists
      stat:
        path: .
      register: repo_exists

    - name: Clone the GitHub repository if it doesn't exist
      git:
        repo: "git@git.is4u.be:stage/stage-2025-ansible-tower/client-configurations.git"
        dest: .
        version: main
      when: not repo_exists.stat.exists
x
    - name: Pull the latest changes if the repository exists
      git:
        repo: "git@git.is4u.be:stage/stage-2025-ansible-tower/client-configurations.git"
        dest: .
        version: main
        update: yes
      when: repo_exists.stat.exists

    - name: Read variables from vars.yml
      include_vars:
        file: client-configurations.yml

    - name: Display variables
      debug:
        msg:
          - "Client Name: {{ client_name }}"
          - "Definition Name: {{ definition_name }}"
          - "Company Name: {{ company_name }}"
          - "Redirect URIs: {{ redirect_uri }}"
          - "Client ID: {{ client_id }}"
          - "Client Secret: {{ client_secret }}"
          - "Require PKCE: {{ require_pkce }}"
          - "Ext Properties: {{ extProperties }}"
