---
- name: Clone or pull GitHub repo and read variables
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Check if the repository exists
      stat:
        path: /tmp/client_configuration
      register: repo_exists

    - name: Clone the GitHub repository
      git:
        repo: "git@git.is4u.be:stage/stage-2025-ansible-tower/client-configurations.git"
        dest: /tmp/client_configuration
        version: main
      when: not repo_exists.stat.exists

    - name: Pull the latest changes if the repository exists
      command: git -C /tmp/client_configuration pull
      register: git_pull_result
      when: repo_exists.stat.exists
      changed_when: "'Already up to date.' not in git_pull_result.stdout"

    - name: Get list of created, updated, and deleted files (only if pull changed)
      command: git -C /tmp/client_configuration diff --name-status HEAD~1 HEAD
      register: git_diff_result
      when: git_pull_result.changed

    - name: Parse git diff output
      set_fact:
        created_files: "{{ git_diff_result.stdout_lines | select('search', '^A\\s+') | map('regex_replace', '^A\\s+', '') | list }}"
        updated_files: "{{ git_diff_result.stdout_lines | select('search', '^M\\s+') | map('regex_replace', '^M\\s+', '') | list }}"
        deleted_files: "{{ git_diff_result.stdout_lines | select('search', '^D\\s+') | map('regex_replace', '^D\\s+', '') | list }}"
      when: git_pull_result.changed

    - name: Display created, updated, and deleted files (only if pull changed)
      debug:
        msg: "{{ {'Created Files': created_files, 'Updated Files': updated_files, 'Deleted Files': deleted_files} }}"
      when: git_pull_result.changed

    - name: Initialize empty clients list
      set_fact:
        clients: []

    - name: Read and transform variables for updated and created files
      rename_vars:
        file_path: "/tmp/client_configuration/{{ item }}"
      register: transformed_clients
      loop: "{{ created_files + updated_files }}"
      when: git_pull_result.changed

    - name: Store transformed variables in clients list
      set_fact:
        clients: "{{ clients + [ {'file': item.item, 'vars': item.transformed_vars} ] }}"
      loop: "{{ transformed_clients.results }}"
      when: git_pull_result.changed

    - name: Display all transformed clients' information in pretty JSON
      debug:
        msg: "{{ clients }}"
      when: git_pull_result.changed

    - name: Save global variables to a file
      copy:
        content: "{{ git_pull_result | to_json }}"
        dest: /tmp/git_pull_result.json

    - name: Save clients to a file
      copy:
        content: "{{ clients | to_json }}"
        dest: /tmp/clients.json

- name: Voeg een OAuth-client toe aan IBM ISAM
  hosts: isam
  gather_facts: no

  tasks:
    - name: Load global variables from file
      set_fact:
        global_git_pull_result: "{{ lookup('file', '/tmp/git_pull_result.json') | from_json }}"
        global_clients: "{{ lookup('file', '/tmp/clients.json') | from_json }}"

    - name: Debug - Controleer de ingeladen clients data
      debug:
        msg: "{{ global_clients }}"

    - name: Transformeer OAuth-client variabelen naar correct formaat
      set_fact:
        formatted_oauth_clients: >-
          {{
            global_clients | map(attribute='vars') | list | map('dict2items') |
            map('map', {'key': 'key | regex_replace("add_oauth_client_", "")', 'value': 'value'}) |
            map('items2dict') |
            map('combine', {
              'add_oauth_client_name': item.name,
              'add_oauth_client_definitionName': item.definition_name,
              'add_oauth_client_companyName': item.company_name,
              'add_oauth_client_redirectUri': item.redirect_uri,
              'add_oauth_client_clientId': item.client_id,
              'add_oauth_client_clientSecret': item.client_secret,
              'add_oauth_client_requirePkce': item.require_pkce
            }) | list
          }}

    - name: Debug - Controleer de getransformeerde OAuth-variabelen
      debug:
        msg: "{{ formatted_oauth_clients }}"

    - name: Add OAuth client based on the transformed variables
      ansible.builtin.include_role:
        name: ibm.isam.add_oauth_client
      vars:
        oauth_clients: "{{ formatted_oauth_clients }}"
      when: global_git_pull_result.changed
