- name: Clone or pull GitHub repo and read variables
  hosts: localhost

  tasks:
    - name: Check if the repository exists
      stat:
        path: /tmp/client_configuration
      register: repo_exists

    - name: Clone the GitHub repository
      git:
        repo: "git@git.is4u.be:stage/stage-2025-ansible-tower/client-configurations.git"
        dest: /tmp/client_configuration
        version: main
      when: not repo_exists.stat.exists

    - name: Pull the latest changes if the repository exists
      command: git -C /tmp/client_configuration pull
      register: git_pull_result
      when: repo_exists.stat.exists
      changed_when: "'Already up to date.' not in git_pull_result.stdout"

    - name: Get list of created, updated, and deleted files (only if pull changed)
      command: git -C /tmp/client_configuration diff --name-status HEAD~1 HEAD
      register: git_diff_result
      when: git_pull_result.changed

    - name: Parse git diff output
      set_fact:
        created_files: "{{ git_diff_result.stdout_lines | select('search', '^A\\s+') | map('regex_replace', '^A\\s+', '') | list }}"
        updated_files: "{{ git_diff_result.stdout_lines | select('search', '^M\\s+') | map('regex_replace', '^M\\s+', '') | list }}"
        deleted_files: "{{ git_diff_result.stdout_lines | select('search', '^D\\s+') | map('regex_replace', '^D\\s+', '') | list }}"
      when: git_pull_result.changed

    - name: Display created, updated, and deleted files (only if pull changed)
      debug:
        msg: "{{ {'Created Files': created_files, 'Updated Files': updated_files, 'Deleted Files': deleted_files} | to_nice_json }}"
      when: git_pull_result.changed

    - name: Initialize empty clients list
      set_fact:
        clients: []

    - name: Read variables for updated and created files and store them in a list
      set_fact:
        clients: "{{ clients + [ {'file': item, 'vars': lookup('file', '/tmp/client_configuration/' + item) | from_yaml } ] }}"
      loop: "{{ created_files + updated_files }}"
      when: git_pull_result.changed

    - name: Display all clients' information in pretty JSON
      debug:
        msg: "{{ clients | to_nice_json }}"
      when: git_pull_result.changed
