---
- name: Pull or update GitHub repo and read variables
  hosts: localhost
  become: yes

  tasks:
    - name: Check if the repository exists
      stat:
        path: client-configurations
      register: repo_exists

    - name: Clone the GitHub repository if it doesn't exist
      git:
        repo: "git@git.is4u.be:stage/stage-2025-ansible-tower/client-configurations.git"
        dest: /home/s1404998
        version: main
      when: not repo_exists.stat.exists

    - name: Pull the latest changes if the repository exists
      git:
        repo: "git@git.is4u.be:stage/stage-2025-ansible-tower/client-configurations.git"
        dest: /home/s140498
        version: main
        update: yes
      when: repo_exists.stat.exists

    - name: Read variables from vars.yml
      include_vars:
        file: client-configurations/DEV/testClient.yml

    - name: Display variables
      debug:
        msg:
          - "Client Name: {{ client_name }}"
          - "Definition Name: {{ definition_name }}"
          - "Company Name: {{ company_name }}"
          - "Redirect URIs: {{ redirect_uri }}"
          - "Client ID: {{ client_id }}"
          - "Client Secret: {{ client_secret }}"
          - "Require PKCE: {{ require_pkce }}"
          - "Ext Properties: {{ extProperties }}"
