- name: Clone or pull GitHub repo and read variables
  hosts: localhost

  tasks:
    - name: Check if the repository exists
      stat:
        path: /tmp/client_configuration
      register: repo_exists

    - name: Clone the GitHub repository
      git:
        repo: "git@git.is4u.be:stage/stage-2025-ansible-tower/client-configurations.git"
        dest: /tmp/client_configuration
        version: main
      when: not repo_exists.stat.exists

    - name: Pull the latest changes if the repository exists
      git:
        repo: "git@git.is4u.be:stage/stage-2025-ansible-tower/client-configurations.git"
        dest: /tmp/client_configuration
        version: main
        update: yes
      when: repo_exists.stat.exists
      register: git_pull_result

    - name: Find all YAML files in DEV folder
      find:
        paths: /tmp/client_configuration/DEV
        patterns: "*.yml"
      register: yaml_files
      # when: git_pull_result.changed

    - name: Read and display variables from each YAML file
      include_vars:
        file: "{{ item.path }}"
      loop: "{{ yaml_files.files }}"
      # when: git_pull_result.changed

    - name: Display variables for each file
      debug:
        msg:
          - "File: {{ item.path }}"
          - "Client Name: {{ client_name | default('N/A') }}"
          - "Definition Name: {{ definition_name | default('N/A') }}"
          - "Company Name: {{ company_name | default('N/A') }}"
          - "Redirect URIs: {{ redirect_uri | default('N/A') }}"
          - "Client ID: {{ client_id | default('N/A') }}"
          - "Client Secret: {{ client_secret | default('N/A') }}"
          - "Require PKCE: {{ require_pkce | default('N/A') }}"
          - "Ext Properties: {{ extProperties | default('N/A') }}"
      loop: "{{ yaml_files.files }}"
      # when: git_pull_result.changed
