- name: Clone of update GitHub repo en lees variabelen
  hosts: localhost
  tasks:
    - name: Controleer of de repository al bestaat
      stat:
        path: /tmp/client_configuration
      register: repo_exists

    - name: Clone de GitHub repository indien nodig
      git:
        repo: "git@git.is4u.be:stage/stage-2025-ansible-tower/client-configurations.git"
        dest: /tmp/client_configuration
        version: main
      when: not repo_exists.stat.exists

    - name: Pull de laatste wijzigingen
      command: git -C /tmp/client_configuration pull
      register: git_pull_result
      when: repo_exists.stat.exists
      changed_when: "'Already up to date.' not in git_pull_result.stdout"

    - name: Bepaal gewijzigde bestanden (alleen bij wijzigingen)
      command: git -C /tmp/client_configuration diff --name-status HEAD~1 HEAD
      register: git_diff_result
      when: git_pull_result.changed

    - name: Parse gewijzigde bestanden
      set_fact:
        created_files: "{{ git_diff_result.stdout_lines | select('search', '^A\\s+') | map('regex_replace', '^A\\s+', '') | list }}"
        updated_files: "{{ git_diff_result.stdout_lines | select('search', '^M\\s+') | map('regex_replace', '^M\\s+', '') | list }}"
        deleted_files: "{{ git_diff_result.stdout_lines | select('search', '^D\\s+') | map('regex_replace', '^D\\s+', '') | list }}"
      when: git_pull_result.changed

    - name: Extraheer verwijderde clientnamen uit bestandsnamen
      set_fact:
        deleted_clients: "{{ deleted_files | map('basename') | map('regex_replace', '\\.yml$', '') | list }}"
      when: git_pull_result.changed

    - name: Lees en transformeer variabelen voor gewijzigde bestanden
      rename_vars:
        file_path: "/tmp/client_configuration/{{ item }}"
      register: transformed_clients
      loop: "{{ created_files + updated_files }}"
      when: git_pull_result.changed

    - name: Sla getransformeerde clients op als fact
      set_fact:
        clients: "{{ transformed_clients.results | map(attribute='transformed_vars') | list }}"
      when: git_pull_result.changed

- name: Voeg (of verwijder) OAuth-clients toe aan IBM ISAM
  hosts: isam
  gather_facts: no
  tasks:
    - name: Controleer of er wijzigingen zijn
      set_fact:
        clients_changed: "{{ hostvars['localhost']['git_pull_result'].changed | default(false) }}"

    - name: Stop als er geen wijzigingen zijn
      meta: end_play
      when: not clients_changed

    - name: Laad getransformeerde clients in
      set_fact:
        global_clients: "{{ hostvars['localhost']['clients'] | default([]) }}"

    - name: Converteer de YAML-strings naar dictionaries
      set_fact:
        global_clients_parsed: "{{ global_clients | map('from_yaml') | list }}"

    - name: Lees de lijst van verwijderde clients
      set_fact:
        deleted_clients: "{{ hostvars['localhost']['deleted_clients'] | default([]) }}"

    - name: Voeg OAuth-client toe met juiste variabelen
      ansible.builtin.include_role:
        name: ibm.isam.set_oauth_client
      loop: "{{ global_clients_parsed }}"
      loop_control:
        loop_var: client
      vars:
        set_oauth_client_clientId: "{{ client.set_oauth_client_clientId }}"
        set_oauth_client_clientSecret: "{{ client.set_oauth_client_clientSecret }}"
        set_oauth_client_companyName: "{{ client.set_oauth_client_companyName }}"
        set_oauth_client_definitionName: "{{ client.set_oauth_client_definitionName }}"
        set_oauth_client_name: "{{ client.set_oauth_client_name }}"
        set_oauth_client_redirectUri: "{{ client.set_oauth_client_redirectUri }}"
        set_oauth_client_requirePkce: "{{ client.set_oauth_client_requirePkce }}"
      when: global_clients | length > 0

    - name: Trigger handler als er clients zijn toegevoegd
      ansible.builtin.debug:
        msg: "Clients zijn toegevoegd, commit de wijzigingen."
      when: global_clients_parsed | length > 0
      notify: Commit Changes

    - name: Stop als er geen verwijderde clients zijn
      meta: end_play
      when: deleted_clients | length == 0

    - name: Verwijder OAuth-client uit ISAM
      ibm.isam.isam:
        log: "{{ log_level | default('INFO') }}"
        force: "{{ force | default(False) }}"
        action: ibmsecurity.isam.aac.api_protection.clients.delete
        isamapi:
          name: "{{ client }}"
      loop: "{{ deleted_clients }}"
      loop_control:
        loop_var: client
