- name: Verwerken van machines
  hosts: machines
  gather_facts: yes
  tasks:
    - name: Voeg tag toe aan succesvolle hosts
      set_fact:
        tagged_as_successful: true

    - name: Voeg gelukte hosts toe aan de groep 'gelukte_hosts'
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: gelukte_hosts
      loop: "{{ ansible_play_hosts }}"
      when: "'tagged_as_successful' in hostvars[item]"

    - name: Toon de verzamelde gelukte hosts
      debug:
        msg: "{{ groups['gelukte_hosts'] }}"

    - name: Toon gefaalde hosts
      run_once: true
      debug:
        msg: "{{ (ansible_play_hosts_all | difference(groups['gelukte_hosts'])) }}"
