- name: Totaalverwerking van machines en variabelen
  hosts: machines
  gather_facts: yes
  become: yes

  vars:
    mislukte_variabelen: []
    mislukte_hosts: []

  tasks:
    - name: Controleer of variabelen fouten veroorzaken
      command: "echo {{ item }}"
      loop: "{{ vars | dict2items | map(attribute='value') | list }}"
      register: variabelen_resultaat
      failed_when: false
      ignore_errors: yes

    - name: Verzamel mislukte variabelen
      set_fact:
        mislukte_variabelen: "{{ mislukte_variabelen + [item.item] }}"
      loop: "{{ variabelen_resultaat.results }}"
      when: item.failed | default(false)

    - name: Voeg tag toe aan succesvolle hosts
      set_fact:
        tagged_as_successful: true

    - name: Voeg gelukte hosts toe aan de groep 'gelukte_hosts'
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: gelukte_hosts
      loop: "{{ ansible_play_hosts }}"
      when: "'tagged_as_successful' in hostvars[item]"

    - name: Verzamel mislukte hosts
      set_fact:
        mislukte_hosts: "{{ ansible_play_hosts_all | difference(groups['gelukte_hosts']) }}"
      run_once: true

    - name: Toon mislukte variabelen
      debug:
        msg: "Mislukte variabelen: {{ mislukte_variabelen }}"
      when: mislukte_variabelen | length > 0

    - name: Toon mislukte hosts
      debug:
        msg: "Mislukte hosts: {{ mislukte_hosts }}"
      when: mislukte_hosts | length > 0

    - name: Verzend mislukte variabelen naar Semaphore
      environmentcreator:
        mislukte_variabelen: "{{ mislukte_variabelen }}"
      when: mislukte_variabelen | length > 0

    - name: Verzend mislukte hosts naar custom inventory module
      inventory:
        mislukte_hosts: "{{ mislukte_hosts }}"
      when: mislukte_hosts | length > 0
      register: output
      run_once: yes
