- name: Toon de gebruiker die het playbook uitvoert
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Haal de huidige gebruiker op
      command: whoami
      register: current_user

    - name: Toon de uitvoerende gebruiker
      debug:
        msg: "Het playbook wordt uitgevoerd door gebruiker: {{ current_user.stdout }}"

    - name: Forceer de SSH_AUTH_SOCK-variabele in Semaphore
      command: echo $SSH_AUTH_SOCK
      register: ssh_agent_sock
      changed_when: false

    - name: Debug SSH_AUTH_SOCK binnen Semaphore
      debug:
        msg: "Semaphore SSH_AUTH_SOCK: {{ ssh_agent_sock.stdout }}"

    - name: Controleer welke SSH-sleutel wordt gebruikt
      command: ssh-add -l
      environment:
        SSH_AUTH_SOCK: "{{ ssh_agent_sock.stdout }}"
      register: ssh_key
      ignore_errors: yes

    - name: Toon de gebruikte SSH-sleutel
      debug:
        msg: "De gebruikte SSH-sleutel(s): {{ ssh_key.stdout_lines }}"
